### ISSUE TITLE
[Bug]: Code View with syntax highlighting throws React unique key warning

### ISSUE THREAD

**Issue by akoreman** [cloudscape-design/code-view#17]
### Browser

Chrome

### Package version

3.0.5

### React version

18.2.0

### Description

When using code view with a syntax highlighting function created by `createHighlight` React throws a warning that not all children in a list are given a unique `key` prop. This can be particularly annoying if you're running unit tests against code view which are set to fail on warnings.

This seems to be coming from `React.Fragment`s being rendered in the `tokens.map(...)` loop [here](https://github.com/cloudscape-design/code-view/blob/main/src/code-view/highlight/index.tsx#L14) without a key explicitly being set to them. Explicitly setting the `key` like is done a couple lines lower [here](https://github.com/cloudscape-design/code-view/blob/main/src/code-view/highlight/index.tsx#L17) should suppress the issue.

PR aiming to fix this: #18

<img width="780" alt="Screenshot 2024-02-20 at 20 29 52" src="https://github.com/cloudscape-design/code-view/assets/34573235/015298ad-dce4-4a28-a973-7b0b9f701a43">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the current issues on [this](https://github.com/cloudscape-design/code-view/issues) and [main](https://github.com/cloudscape-design/components/issues) repositories for duplicate problems

**Comment by rubencarvalho** [comment]
Thank you for reporting and for your bias for action on opening the respective pull request. We added a small comment to the PR but we'll gladly merge the changes.

**Comment by rubencarvalho** [comment]
Fixed with https://github.com/cloudscape-design/code-view/pull/18
